config/routes.rb
UIFinalProject::Application.routes.draw do  
  root :to => "users#splash"

  resources :users do
    resources :courses
    resources :links
    resources :accomplishments
    resources :papers
    resources :researches
    resources :educations
  end
  
  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'learn' => 'users#learn', :as => :learn
end

app/models/research.rb
class Research < ActiveRecord::Base
  attr_accessible :title, :link, :description, :user_id
  belongs_to :user
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
  before_filter :login_required, :except => [:show]
  before_filter :find_research, :only => [:show, :edit, :update, :destroy]
  def index
    @researches = Research.all
  end

  def show
    #@research = Research.find(params[:id])
  end

  def new
    @research = Research.new
  end

  def create
    @research = Research.new(params[:research])
    @research.user = current_user
    if @research.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user), :notice => "Successfully created research." }
        format.js 
      end
    else
      render :action => 'new'
    end
  end

  def edit
    @research = Research.find(params[:id])
  end

  def update
    @research = Research.find(params[:id])
    if @research.update_attributes(params[:research])
      redirect_to current_user, :notice  => "Successfully updated research."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @research = Research.find(params[:id])
    @research.destroy
  end
  
  private
    def find_research
      @research = Research.find(params[:id])
    end
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/researches/_form.html.erb
<%= form_for [current_user, @research] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/researches/_research.html.haml
= content_tag_for( :li, research ) do
  -if research.user == current_user
    .modifiers
      = link_to "Edit research", edit_user_research_path(current_user,research)
      = link_to "Delete research", user_research_path(current_user,research), :remote => true, :confirm => 'Are you sure?', :method => :delete 
  = link_to research.title, research.link

app/views/researches/create.js.erb
$('#researches').prepend('<%= escape_javascript(render(@research)) %>');
$('#researches > li:first').hide().slideDown().effect('highlight', {}, 3000);

app/views/researches/destroy.js.erb
$('#<%= dom_id @research %>').animate({ height: 0, opacity: 0 }, 'slow');

app/views/researches/edit.html.erb
<% title "Edit Research" %>

<%= render 'form' %>

app/views/researches/index.html.erb
<% title "Researches" %>

<table>
  <tr>
    <th>Title</th>
    <th>Link</th>
    <th>Description</th>
  </tr>
  <% for research in @researches %>
    <tr>
      <td><%= research.title %></td>
      <td><%= research.link %></td>
      <td><%= research.description %></td>
      <td><%= link_to "Show", user_research_path(current_user,research) %></td>
      <td><%= link_to "Edit", edit_user_research_path(current_user,research) %></td>
      <td><%= link_to "Destroy", user_research_path(current_user,research), :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Research", new_user_research_path(current_user) %></p>

app/views/researches/new.html.erb
<% title "New Research" %>

<%= render 'form' %>

<p><%= link_to "Back to List",user_path(current_user) %></p>

app/views/researches/show.html.erb
<% title "Research" %>

<p>
  <strong>Title:</strong>
  <%= @research.title %>
</p>
<p>
  <strong>Link:</strong>
  <%= @research.link %>
</p>
<p>
  <strong>Description:</strong>
  <%= @research.description %>
</p>

<p>
  <%= link_to "Edit", edit_research_path(@research) %> |
  <%= link_to "Destroy", @research, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", researches_path %>
</p>