config/routes.rb
UIFinalProject::Application.routes.draw do  
  root :to => "users#splash"

  resources :users do
    resources :courses
    resources :links
    resources :accomplishments
    resources :papers
    resources :researches
    resources :educations
  end
  
  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'learn' => 'users#learn', :as => :learn
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :username, :email, :title, :name, :office, :department, :phone_number, :bio
  acts_as_authentic
  
  has_many :courses
  has_many :papers
  has_many :educations
  has_many :researches
 
  #it's really more of a has_one relationship
  #but ActiveRecord's careful fluent language
  #breaks down here
  belongs_to :style

  self.per_page = 10
  
  def full_name
    "#{self.title} #{self.name}"
  end
  
  def to_s
    self.full_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :only => [:edit, :update]
  before_filter :find_user, :only => [:edit, :update]

  def new
    @user = User.new
  end
  
  def splash
    if current_user #redirect to user's homepage
      @user = current_user
      render :show
    end
  end
  
  def learn
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, :notice => "Thank you for signing up! Now it's time to create your persona."
    else
      render :action => 'new'
    end
  end
  
  def index
    @users = User.where(:published => true).paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    if !@user.published? and @user != current_user
      redirect_to :root, :notice => "That user hasn't published their persona"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      if params[:ajax]
        render :text => @user.bio 
      else
        redirect_to @user, :notice => "Your profile has been updated."
      end
    else
      render :action => 'edit'
    end
  end
  
  private

  def find_user
    @user = current_user
  end

  def current_user?
    current_user == @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?
    current_user == @user
  end
end

app/views/users/_content.html.haml
-content_for :style_name do
  = "#{@user.style.stylesheet}"

#prof-info

  .content-section
    %h3 Contact Information
    -#%ul#contact_info
    -if @user.office?
      %p Office: #{@user.office}
    -if @user.phone_number?
      %p Phone Number: #{@user.phone_number}
    -if @user.email?
      %p Email: #{@user.email}
  

  -if @user.bio.length != 0
    .content-section
      %h3 Biography
      %p#bio= @user.bio

  -if @user.courses.length != 0
    .content-section
      %h3 Courses
      %ul#courses
        - for course in @user.courses
          %p #{course.title}
 
  -if @user.papers.length != 0     
    .content-section
      %h3 Papers and Publications
      %ul#papers
      -for paper in @user.papers
        %p #{paper.title}

  -if @user.educations.length != 0
    .content-section
      %h3 Education
      %ul#educations
      -for education in @user.educations
        %p #{education.degree}

  -if @user.researches.length != 0
    .content-section
      %h3 Research
      %ul#researches
      -for research in @user.researches
        %p #{research.title}

app/views/users/_form.html.haml
- if logged_in?
  = semantic_form_for @user do |f|
    = f.error_messages
    = f.inputs @user.published? ? "Need to unpublish your persona?" : "Ready to publish your persona for public viewing?" do 
      = f.input :published, :as => :radio, :collection => {"Published" => true, "Draft" => false}, :hint => @user.published? ? "Marking your persona as a draft will make it no longer publicly viewable." : "Once you've entered all the information you want, publish it so the world can see you!"
    = f.inputs "Choose a style for your page" do
      = f.input :style, :as => :radio
    = f.inputs "Add your Twitter Feed", :twitter_username
    = f.inputs "Account Settings" do
      = f.input :username, :required => false
      = f.input :email, :required => false
      = f.input :password, :required => false
      = f.input :password_confirmation, :required => false
      = f.input :name, :required => false
      = f.input :title, :required => false
    = f.buttons
- else
  = semantic_form_for @user do |f|
    = f.error_messages
    = f.inputs :name, :title, :email, :username, :password, :password_confirmation
    = f.buttons 

app/views/users/_twitter.html.erb
<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 'auto',
  height: 300,
  theme: {
    shell: {
      background: '#dedede',
      color: '#000000'
    },
    tweets: {
      background: '#ffffff',
      color: '#000000',
      links: '#0024b3'
    }
  },
  features: {
    scrollbar: true,
    loop: true,
    live: true,
    behavior: 'default'
  }
}).render().setUser('<%= @user.twitter_username %>').start();
</script>

app/views/users/_user.html.haml
-content_for :style_name do
  = "#{@user.style.stylesheet}"

#prof-info
  .content-section
    -if current_user == @user
      %h3.logged-in Contact Information
      .add-element
        =link_to "Edit Contact Info", edit_user_path(current_user), :class => "button positive"
      .clear
    -else
      %h3 Contact Information
    -#%ul#contact_info
    -if @user.office?
      %p Office: #{@user.office}
    -if @user.phone_number?
      %p Phone Number: #{@user.phone_number}
    -if @user.email?
      %p Email: #{@user.email}

  - if @user.bio? or current_user == @user
    .content-section
      .clearfix
        -if current_user == @user
          %h3.logged-in Biography
          %button.add-element.positive#edit-biography Edit Biography
          .clear
          %p#bio= editable_field @user, :bio, :submitdata => { :ajax => true }, :type => 'textarea', :submit => 'Update', :cancel => 'Cancel', :tooltip => 'Click to edit', :indicator => 'Saving...'
        -else
          %h3 Biography
          %p#bio= @user.bio
        
  - if @user.courses.count > 0 or current_user == @user 
    .content-section
      -if current_user == @user
        %h3.logged-in Courses
        .add-element
          =button_to "+Add Course", user_courses_path(@user), :method => :post, :remote => true, :class => "button positive"
        .clear
      -else
        %h3 Courses
      %ul#courses
        = render @user.courses

  - if @user.papers.count > 0 or current_user == @user
    .content-section
      -if current_user == @user
        %h3.logged-in Papers and Publications
        .add-element
          =button_to "+Add Paper", user_papers_path(@user), :method => :post, :remote => true, :class => "button positive"
        .clear
      -else
        %h3 Papers and Publications
      %ul#papers
        = render @user.papers

  - if @user.educations.count > 0 or current_user == @user
    .content-section
      -if current_user == @user
        %h3.logged-in Education
        .add-element
          =button_to "+Add School", user_educations_path(@user), :method => :post, :remote => true, :class => "button positive"
        .clear
      -else
        %h3 Research
      %ul#educations
        = render @user.educations

  - if @user.researches.count > 0 or current_user == @user
    .content-section
      -if current_user == @user
        %h3.logged-in Research
        .add-element
          =button_to "+Add Research", user_researches_path(@user), :method => :post, :remote => true, :class => "button positive"
        .clear
      -else
        %h3 Research
      %ul#researches
        = render @user.researches
  - if !@user.twitter_username.to_s.empty?
    .content-section
      %h3 Twitter
      = render "twitter"

app/views/users/edit.html.haml
- title "Edit your Profile"

-content_for :style_name do
  = "#{@user.style.stylesheet}"

.clear

= render 'form'

app/views/users/index.html.haml
- title "Professors"

.clear

#info
  %h3 Explore
  %p Curious as to what makes a great professor page?  Need inspiration?  Check out some examples from your peers to get a better idea.
  
- unless @users.count == 0
  = will_paginate @users
  %ul
    - @users.each do |user|
      %li.buttons= link_to user, user
- else
  #zero-count 
    %h3 Oops!  
    It looks like no professors have published their personas yet!

- if logged_in?  
  %h4 Enough inspiration?
  = link_to "Back to your persona", current_user, :class => "button positive"

app/views/users/learn.html.haml
-title "Welcome!"

.clear

.content-section#introduction
  %h2 Out with the old.
  .clear
  Maybe you've created a personal page sometime in the past, and it looked something like this:
  .clear
  %br
  = image_tag "pre-page.png", :style => "border: 1px solid grey; padding: .5em; margin: .5em;"
  .clear
  %br
  %h2 In with the new.
  .clear
  Use Pr.fess.r to put a fresh coat of paint on your personal "about me" page.  
  .clear
  %br
  = image_tag "post-page.png", :style => "border: 1px solid grey; padding: .5em; margin: .5em;"
  
  .clear
  = link_to "Sign up now", signup_path, :class => "button positive"
  = link_to "View sample personas", users_path, :class => "buton positive"

app/views/users/new.html.haml
- title "Sign up"

.clear

#info 
  Already have an account? 
  =link_to "Log in", login_path

= render 'form'

app/views/users/show.html.haml
-title "#{@user.title} #{@user.name}"
- if !request.referer.nil? and URI(request.referer).path == signup_path
  #info
    %h3 Welcome to your new page!
    %p Let's get started.
    %ol
      %li Add in some information about yourself here 
      %li Rearrange your content
      %li Choose a style  
    %p When you're ready for prime time change your persona from "draft" to "publish".  Make sure to click Update!

- if show_title?
  %h2= yield(:title)

- if current_user?
  = link_to "Edit account information", edit_user_path(current_user), :class => "button positive edit"
  
- if !@user.published? and current_user?
  .clear
  .notice
    %h3 Draft Status
    Your persona is currently in draft status.  Until you publish (click "edit account information" above) students will not be able to view your persona.

- if @user.published? or current_user?
  = render @user

-if logged_in?
  - if current_user?
    %h4 Curious what other professors' personas look like?
    = link_to "View other Professors",users_path, :class => "button positive"
  - else
    %h4 Enough inspiration?
    = link_to "Back to your persona",user_path(current_user), :class => "button positive"

app/views/users/splash.html.haml
-title "Welcome!"

.clear

.content-section#introduction
  %h2 Your twenty-first century business card. 
  .clear
  %p Need to create a simple, online "about me" page?  Pr.fess.r is the answer.
  %p Create an easy, elegant, and stylish web persona with just a few clicks, or look around and see what other professors like you have created.
  .clear
  = link_to "Learn more", learn_path, :class => "button positive"
  = link_to "Sign up now", signup_path, :class => "button positive"
  = link_to "View sample personas", users_path, :class => "buton positive"