config/routes.rb
UIFinalProject::Application.routes.draw do  
  root :to => "users#splash"

  resources :users do
    resources :courses
    resources :links
    resources :accomplishments
    resources :papers
    resources :researches
    resources :educations
  end
  
  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'learn' => 'users#learn', :as => :learn
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  attr_accessible :user_id, :title, :authors, :publisher, :date, :page_count, :link
  
  belongs_to :user
  
  def does_paper_exist
    # Check to see if paper is exists. Check that link isn't broken
    
  end
  
  def get_info
    # Follow link and see what extra details you can get from link.
    
    # Title
    
    # Author(s)
    
    # Abstract?
  end
  
  def to_s
    "#{self.title}"
  end
  
end

app/controllers/members/papers_controller.rb
class Members::PapersController < ApplicationController
  before_filter :login_required
  before_filter :find_paper, :only => [:show, :edit, :update, :destroy]

  def index
    @papers = Paper.all
  end

  def show
  end

  def new
    @paper = Paper.new
  end

  def create
    @paper = Paper.new(params[:paper])
    @paper.user = current_user
    if @paper.save
      #format.html { redirect_to edit_members_user_path(@paper.user), :notice => "Successfully created paper." }
	    render :json => @paper
	  else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @paper.update_attributes(params[:paper])
      #redirect_to edit_members_user_path(@paper.user), :notice  => "Successfully updated paper." }
	    render :text => @paper.title
    else
      render :action => 'edit'
    end
  end

  def destroy
    @paper.destroy
    #redirect_to edit_members_user_path(@paper.user), :notice => "Successfully destroyed paper."
	render :text => 'destroyed'
  end
  
  private
    
    def find_paper
      @paper = Paper.find(params[:id])
    end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_filter :login_required, :except => [:show]
  before_filter :find_paper, :only => [:show, :edit, :update, :destroy]

  def index
    @papers = Paper.all
  end

  def show
  end

  def new
    @paper = Paper.new
  end

  def create
    @paper = Paper.new(params[:paper])
    @paper.user = current_user
    if @paper.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user), :notice => "Successfully created course." }
        format.js 
      end
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @paper.update_attributes(params[:paper])
      redirect_to @paper.user, :notice  => "Successfully updated paper."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @paper.destroy
  end
  
  private
    
    def find_paper
      @paper = Paper.find(params[:id])
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.haml
= form_for [current_user, @paper] do |f|
  = f.error_messages
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :authors
    %br
    = f.text_field :authors
  %p
    = f.label :publisher
    %br
    = f.text_field :publisher
  %p
    = f.label :date_published
    %br
    = f.text_field :date_published
  %p
    = f.label :page_count
    %br
    = f.text_field :date_published
  %p
    = f.label :link
    %br
    = f.text_field :link, :value => "http://"
  %p
    = f.submit

app/views/papers/_paper.html.haml
= content_tag_for :li, paper do
  -if paper.user == current_user
    .modifiers
      = link_to "Edit Paper", edit_user_paper_path(current_user,paper)
      = link_to "Delete Paper", user_paper_path(current_user,paper), :remote => true, :confirm => 'Are you sure?', :method => :delete 
  %p= link_to paper.title, paper.link

app/views/papers/create.js.erb
$('#papers').prepend('<%= escape_javascript(render(@paper)) %>');
$('#papers > li:first').hide().slideDown().effect('highlight', {}, 3000);

app/views/papers/destroy.js.erb
$('#<%= dom_id @paper %>').animate({ height: 0, opacity: 0 }, 'slow');

app/views/papers/edit.html.haml
- title "Edit Paper"

= render 'form'

%p
  = link_to "Show", user_paper_path(current_user,@paper)
  |
  = link_to "View All", user_papers_path

app/views/papers/index.html.haml
- title "Papers"

%table
  %tr
    %th User
    %th Title
  - for paper in @papers
    %tr
      %td= paper.user_id
      %td= paper.title
      %td= link_to 'Show', paper_path(paper)
      %td= link_to 'Edit', edit_paper_path(paper)
      %td= link_to 'Destroy',paper_path(paper), :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Paper", new_user_paper_path

app/views/papers/new.html.haml
- title "New Paper"

= render 'form'

%p= link_to "Back to your profile", edit_user_path(current_user), :class => "button positive"

app/views/papers/show.html.haml
- title "Paper"

%p
  %strong User:
  = @paper.user
%p
  %strong Title:
  = @paper.title

%p
  = link_to "Edit", edit_user_paper_path(@paper)
  |
  = link_to "Destroy",user_paper_path(@paper), :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All",user_papers_path