config/routes.rb
UIFinalProject::Application.routes.draw do  
  root :to => "users#splash"

  resources :users do
    resources :courses
    resources :links
    resources :accomplishments
    resources :papers
    resources :researches
    resources :educations
  end
  
  resources :user_sessions
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'learn' => 'users#learn', :as => :learn
end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :university, :degree, :year, :city, :state, :country, :user_id
  belongs_to :user

  def to_s
    "#{year} -- Degree in #{degree} at #{university}"
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_filter :login_required, :except => [:show]
  before_filter :find_education, :only => [:show, :edit, :update, :destroy]
  
  def index
    @educations = Education.all
  end

  def show
  end

  def new
    @education = Education.new
  end

  def create
    @education = Education.new(params[:education])
    @education.user = current_user
    if @education.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user), :notice => "Successfully created education." }
        format.js 
      end
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    @education = Education.find(params[:id])
    if @education.update_attributes(params[:education])
      redirect_to @education.user, :notice  => "Successfully updated education."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @education.destroy
  end
  
  protected
  
    def find_education
      @education = Education.find(params[:id])
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_education.html.haml
= content_tag_for( :li, education ) do
  -if education.user == current_user
    .modifiers
      = link_to "Edit education", edit_user_education_path(current_user,education)
      = link_to "Delete education", user_education_path(current_user,education), :remote => true, :confirm => 'Are you sure?', :method => :delete 
  %span= education

app/views/educations/_form.html.erb
<%= form_for [current_user, @education] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :university %><br />
    <%= f.text_field :university %>
  </p>
  <p>
    <%= f.label :degree %><br />
    <%= f.text_field :degree %>
  </p>
  <p>
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/educations/create.js.erb
$('#educations').prepend('<%= escape_javascript(render(@education)) %>');
$('#educations > li:first').hide().slideDown().effect('highlight', {}, 3000);

app/views/educations/destroy.js.erb
$('#<%= dom_id @education %>').animate({ height: 0, opacity: 0 }, 'slow');

app/views/educations/edit.html.erb
<% title "Edit Education" %>

<%= render 'form' %>

app/views/educations/index.html.erb
<% title "Educations" %>

<table>
  <tr>
    <th>University</th>
    <th>Degree</th>
    <th>Year</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
  </tr>
  <% for education in @educations %>
    <tr>
      <td><%= education.university %></td>
      <td><%= education.degree %></td>
      <td><%= education.year %></td>
      <td><%= education.city %></td>
      <td><%= education.state %></td>
      <td><%= education.country %></td>
      <td><%= link_to "Show", education %></td>
      <td><%= link_to "Edit", edit_education_path(education) %></td>
      <td><%= link_to "Destroy", education, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Education", new_education_path %></p>

app/views/educations/new.html.erb
<% title "New Education" %>

<%= render 'form' %>

<p><%= link_to "Back to List", current_user %></p>

app/views/educations/show.html.erb
<% title "Education" %>

<p>
  <strong>University:</strong>
  <%= @education.university %>
</p>
<p>
  <strong>Degree:</strong>
  <%= @education.degree %>
</p>
<p>
  <strong>Year:</strong>
  <%= @education.year %>
</p>
<p>
  <strong>City:</strong>
  <%= @education.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @education.state %>
</p>
<p>
  <strong>Country:</strong>
  <%= @education.country %>
</p>

<p>
  <%= link_to "Edit", edit_education_path(@education) %> |
  <%= link_to "Destroy", @education, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", educations_path %>
</p>